-- Airline ticketing schema bootstrap script for Oracle 12c
-- Run as the schema owner (one time) to create all tables, constraints,
-- sequences, PL/SQL objects and sample data.

SET DEFINE OFF;

PROMPT Dropping old objects (ignoring errors)...
BEGIN
  FOR rec IN (SELECT object_name, object_type
              FROM user_objects
              WHERE object_type IN ('TABLE', 'SEQUENCE', 'PACKAGE', 'PACKAGE BODY', 'FUNCTION', 'PROCEDURE', 'VIEW', 'TRIGGER'))
  LOOP
    BEGIN
      EXECUTE IMMEDIATE 'DROP ' || rec.object_type || ' "' || rec.object_name || '" CASCADE';
    EXCEPTION
      WHEN OTHERS THEN NULL;
    END;
  END LOOP;
END;
/

PROMPT Creating tables...

CREATE TABLE airport (
  airport_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  airport_code   CHAR(3) NOT NULL UNIQUE,
  name           VARCHAR2(100) NOT NULL,
  city           VARCHAR2(80) NOT NULL,
  country        VARCHAR2(80) NOT NULL
);

CREATE TABLE aircraft (
  aircraft_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  model          VARCHAR2(60) NOT NULL,
  tail_number    VARCHAR2(20) UNIQUE,
  total_seats    NUMBER NOT NULL
);

CREATE TABLE route (
  route_id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  departure_airport_id   NUMBER NOT NULL REFERENCES airport(airport_id),
  arrival_airport_id     NUMBER NOT NULL REFERENCES airport(airport_id),
  distance_km            NUMBER,
  economy_fare           NUMBER(8,2) NOT NULL,
  business_fare          NUMBER(8,2) NOT NULL,
  first_fare             NUMBER(8,2) NOT NULL
);

CREATE TABLE flight (
  flight_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  route_id       NUMBER NOT NULL REFERENCES route(route_id),
  flight_number  VARCHAR2(10) NOT NULL,
  departure_ts   TIMESTAMP NOT NULL,
  arrival_ts     TIMESTAMP NOT NULL,
  aircraft_id    NUMBER NOT NULL REFERENCES aircraft(aircraft_id),
  status         VARCHAR2(20) DEFAULT 'SCHEDULED'
);

CREATE TABLE seat_layout (
  seat_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  flight_id         NUMBER NOT NULL REFERENCES flight(flight_id) ON DELETE CASCADE,
  cabin_class       VARCHAR2(20) NOT NULL,
  seat_row          NUMBER NOT NULL,
  seat_col          CHAR(1) NOT NULL,
  seat_no           VARCHAR2(4) NOT NULL,
  is_exit_row       CHAR(1) DEFAULT 'N',
  is_extra_legroom  CHAR(1) DEFAULT 'N',
  is_wheelchair     CHAR(1) DEFAULT 'N',
  CONSTRAINT uq_seat UNIQUE (flight_id, seat_no)
);

CREATE TABLE customer (
  customer_id   NUMBER PRIMARY KEY,
  full_name     VARCHAR2(120) NOT NULL,
  contact_info  VARCHAR2(120),
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE booking (
  booking_id    NUMBER PRIMARY KEY,
  customer_id   NUMBER NOT NULL REFERENCES customer(customer_id),
  flight_id     NUMBER NOT NULL REFERENCES flight(flight_id),
  pnr_code      VARCHAR2(6) NOT NULL UNIQUE,
  status        VARCHAR2(20) DEFAULT 'CONFIRMED',
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP,
  paid_flag     CHAR(1) DEFAULT 'N'
);

CREATE TABLE ticket (
  ticket_id      NUMBER PRIMARY KEY,
  booking_id     NUMBER NOT NULL REFERENCES booking(booking_id),
  flight_id      NUMBER NOT NULL REFERENCES flight(flight_id),
  ticket_number  VARCHAR2(20) NOT NULL UNIQUE,
  seat_no        VARCHAR2(4) NOT NULL,
  cabin_class    VARCHAR2(20) NOT NULL,
  fare_amount    NUMBER(10,2) NOT NULL,
  status         VARCHAR2(20) DEFAULT 'ACTIVE',
  issued_at      TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE payment (
  payment_id   NUMBER PRIMARY KEY,
  booking_id   NUMBER NOT NULL REFERENCES booking(booking_id),
  amount       NUMBER(10,2) NOT NULL,
  method       VARCHAR2(20),
  status       VARCHAR2(20) DEFAULT 'PAID',
  created_at   TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE ticket_audit (
  audit_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id     NUMBER NOT NULL,
  action        VARCHAR2(20) NOT NULL,
  seat_no       VARCHAR2(4),
  action_ts     TIMESTAMP DEFAULT SYSTIMESTAMP
);

PROMPT Creating sequences...

CREATE SEQUENCE seq_customer START WITH 1000 NOCACHE;
CREATE SEQUENCE seq_booking START WITH 2000 NOCACHE;
CREATE SEQUENCE seq_ticket START WITH 3000 NOCACHE;
CREATE SEQUENCE seq_payment START WITH 4000 NOCACHE;

PROMPT Creating triggers for PK defaults and audits...

CREATE OR REPLACE TRIGGER trg_customer_pk
BEFORE INSERT ON customer
FOR EACH ROW
WHEN (NEW.customer_id IS NULL)
BEGIN
  :NEW.customer_id := seq_customer.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER trg_booking_pk
BEFORE INSERT ON booking
FOR EACH ROW
WHEN (NEW.booking_id IS NULL)
BEGIN
  :NEW.booking_id := seq_booking.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER trg_ticket_pk
BEFORE INSERT ON ticket
FOR EACH ROW
WHEN (NEW.ticket_id IS NULL)
BEGIN
  :NEW.ticket_id := seq_ticket.NEXTVAL;
  :NEW.ticket_number := '300' || TO_CHAR(seq_ticket.CURRVAL);
END;
/

CREATE OR REPLACE TRIGGER trg_payment_pk
BEFORE INSERT ON payment
FOR EACH ROW
WHEN (NEW.payment_id IS NULL)
BEGIN
  :NEW.payment_id := seq_payment.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER trg_ticket_audit
AFTER INSERT OR UPDATE OR DELETE ON ticket
FOR EACH ROW
DECLARE
  v_action VARCHAR2(20);
  v_seat   VARCHAR2(4);
BEGIN
  IF INSERTING THEN
    v_action := 'INSERT';
    v_seat := :NEW.seat_no;
  ELSIF UPDATING THEN
    v_action := 'UPDATE';
    v_seat := :NEW.seat_no;
  ELSE
    v_action := 'DELETE';
    v_seat := :OLD.seat_no;
  END IF;

  INSERT INTO ticket_audit(ticket_id, action, seat_no)
  VALUES (NVL(:NEW.ticket_id, :OLD.ticket_id), v_action, v_seat);
END;
/

PROMPT Creating indexes...

CREATE INDEX idx_flight_route_time ON flight(route_id, departure_ts);
CREATE INDEX idx_ticket_flight ON ticket(flight_id);
CREATE INDEX idx_booking_customer ON booking(customer_id);

PROMPT Sample master data...

INSERT INTO airport(airport_code, name, city, country)
VALUES ('YYZ', 'Toronto Pearson', 'Toronto', 'Canada');
INSERT INTO airport(airport_code, name, city, country)
VALUES ('YVR', 'Vancouver Intl', 'Vancouver', 'Canada');
INSERT INTO airport(airport_code, name, city, country)
VALUES ('YUL', 'Montreal Trudeau', 'Montreal', 'Canada');
INSERT INTO airport(airport_code, name, city, country)
VALUES ('LAX', 'Los Angeles Intl', 'Los Angeles', 'USA');
INSERT INTO airport(airport_code, name, city, country)
VALUES ('JFK', 'John F. Kennedy', 'New York', 'USA');

INSERT INTO aircraft(model, tail_number, total_seats)
VALUES ('Boeing 787-9', 'C-ABC1', 290);
INSERT INTO aircraft(model, tail_number, total_seats)
VALUES ('Airbus A321', 'C-XYZ2', 190);

INSERT INTO route(departure_airport_id, arrival_airport_id, distance_km, economy_fare, business_fare, first_fare)
SELECT dep.airport_id, arr.airport_id, 3358, 320, 980, 1600
FROM airport dep, airport arr
WHERE dep.airport_code = 'YYZ' AND arr.airport_code = 'YVR';

INSERT INTO route(departure_airport_id, arrival_airport_id, distance_km, economy_fare, business_fare, first_fare)
SELECT dep.airport_id, arr.airport_id, 500, 180, 620, 950
FROM airport dep, airport arr
WHERE dep.airport_code = 'YYZ' AND arr.airport_code = 'YUL';

INSERT INTO flight(route_id, flight_number, departure_ts, arrival_ts, aircraft_id, status)
VALUES (1, 'AC101', TO_TIMESTAMP('2024-05-21 08:30', 'YYYY-MM-DD HH24:MI'), TO_TIMESTAMP('2024-05-21 10:45', 'YYYY-MM-DD HH24:MI'), 1, 'SCHEDULED');

INSERT INTO flight(route_id, flight_number, departure_ts, arrival_ts, aircraft_id, status)
VALUES (1, 'AC105', TO_TIMESTAMP('2024-05-21 16:00', 'YYYY-MM-DD HH24:MI'), TO_TIMESTAMP('2024-05-21 18:15', 'YYYY-MM-DD HH24:MI'), 1, 'SCHEDULED');

INSERT INTO flight(route_id, flight_number, departure_ts, arrival_ts, aircraft_id, status)
VALUES (2, 'AC410', TO_TIMESTAMP('2024-05-21 09:30', 'YYYY-MM-DD HH24:MI'), TO_TIMESTAMP('2024-05-21 10:42', 'YYYY-MM-DD HH24:MI'), 2, 'SCHEDULED');

PROMPT Adding dynamic-dated flights (today and next 2 days)...

DECLARE
  v_base TIMESTAMP := CAST(TRUNC(SYSDATE) AS TIMESTAMP);
BEGIN
  -- Today YYZ->YVR
  INSERT INTO flight(route_id, flight_number, departure_ts, arrival_ts, aircraft_id, status)
  VALUES (1, 'AC201', v_base + (8/24), v_base + (10.5/24), 1, 'SCHEDULED');

  INSERT INTO flight(route_id, flight_number, departure_ts, arrival_ts, aircraft_id, status)
  VALUES (1, 'AC203', v_base + (15/24), v_base + (17.5/24), 1, 'SCHEDULED');

  -- Tomorrow YYZ->YVR
  INSERT INTO flight(route_id, flight_number, departure_ts, arrival_ts, aircraft_id, status)
  VALUES (1, 'AC205', v_base + 1 + (9/24), v_base + 1 + (11.5/24), 1, 'SCHEDULED');

  -- Today YYZ->YUL
  INSERT INTO flight(route_id, flight_number, departure_ts, arrival_ts, aircraft_id, status)
  VALUES (2, 'AC411', v_base + (7.5/24), v_base + (8.7/24), 2, 'SCHEDULED');

  -- Tomorrow YYZ->YUL
  INSERT INTO flight(route_id, flight_number, departure_ts, arrival_ts, aircraft_id, status)
  VALUES (2, 'AC413', v_base + 1 + (18/24), v_base + 1 + (19.2/24), 2, 'SCHEDULED');
END;
/

PROMPT Generating seat layout per flight...

DECLARE
  PROCEDURE add_seat(p_flight NUMBER, p_row NUMBER, p_label CHAR, p_cabin VARCHAR2, p_exit CHAR := 'N', p_extra CHAR := 'N') IS
  BEGIN
    INSERT INTO seat_layout(flight_id, cabin_class, seat_row, seat_col, seat_no, is_exit_row, is_extra_legroom)
    VALUES (p_flight, p_cabin, p_row, p_label, TO_CHAR(p_row) || p_label, p_exit, p_extra);
  END;
BEGIN
  FOR rec IN (SELECT flight_id FROM flight) LOOP
    -- Business cabin rows 7-16 seats A-D-G-J (2-2-2)
    FOR row_num IN 7 .. 16 LOOP
      add_seat(rec.flight_id, row_num, 'A', 'BUSINESS');
      add_seat(rec.flight_id, row_num, 'D', 'BUSINESS');
      add_seat(rec.flight_id, row_num, 'G', 'BUSINESS');
      add_seat(rec.flight_id, row_num, 'J', 'BUSINESS');
    END LOOP;

    -- Economy cabin rows 28-36 seats ABC-DEF-GHJ
    FOR row_num IN 28 .. 36 LOOP
      FOR seat_label IN ('A','B','C','D','E','F','G','H','J') LOOP
        add_seat(rec.flight_id, row_num, seat_label, 'ECONOMY',
          CASE WHEN row_num IN (28, 36) THEN 'Y' ELSE 'N' END,
          CASE WHEN row_num IN (28, 29) THEN 'Y' ELSE 'N' END);
      END LOOP;
    END LOOP;

    -- First cabin rows 1-4 seat H style
    FOR row_num IN 1 .. 4 LOOP
      add_seat(rec.flight_id, row_num, 'A', 'FIRST');
      add_seat(rec.flight_id, row_num, 'D', 'FIRST');
      add_seat(rec.flight_id, row_num, 'G', 'FIRST');
      add_seat(rec.flight_id, row_num, 'J', 'FIRST');
    END LOOP;
  END LOOP;
END;
/

PROMPT Loading sample passengers + bookings...

INSERT INTO customer(customer_id, full_name, contact_info)
VALUES (seq_customer.NEXTVAL, 'Alice Park', 'alice@example.com');

INSERT INTO customer(customer_id, full_name, contact_info)
VALUES (seq_customer.NEXTVAL, 'Brian Lee', 'brian@example.com');

INSERT INTO booking(booking_id, customer_id, flight_id, pnr_code, status, paid_flag)
VALUES (seq_booking.NEXTVAL, 1000, 1, 'A1B2C3', 'CONFIRMED', 'Y');

INSERT INTO ticket(ticket_id, booking_id, flight_id, seat_no, cabin_class, fare_amount, status)
VALUES (seq_ticket.NEXTVAL, 2000, 1, '28A', 'ECONOMY', 320, 'ACTIVE');

PROMPT Additional sample bookings for today/tomorrow flights...
DECLARE
  PROCEDURE add_booking(p_name VARCHAR2, p_contact VARCHAR2, p_flight_id NUMBER, p_seat VARCHAR2, p_cabin VARCHAR2, p_fare NUMBER) IS
    v_pnr booking.pnr_code%TYPE;
  BEGIN
    v_pnr := DBMS_RANDOM.STRING('A', 3) || LPAD(TO_CHAR(DBMS_RANDOM.VALUE(0, 999)), 3, '0');

    INSERT INTO customer(customer_id, full_name, contact_info)
    VALUES (seq_customer.NEXTVAL, p_name, p_contact);

    INSERT INTO booking(booking_id, customer_id, flight_id, pnr_code, status, paid_flag)
    VALUES (seq_booking.NEXTVAL, seq_customer.CURRVAL, p_flight_id, v_pnr, 'CONFIRMED', 'Y');

    INSERT INTO ticket(ticket_id, booking_id, flight_id, seat_no, cabin_class, fare_amount, status)
    VALUES (seq_ticket.NEXTVAL, seq_booking.CURRVAL, p_flight_id, p_seat, p_cabin, p_fare, 'ACTIVE');
  END;
BEGIN
  -- Use actual flight IDs based on insertion order: first 3 static, then dynamic block (today/tomorrow)
  -- Assuming dynamic YYZ-YVR flights got IDs 4,5,6 and YYZ-YUL 7,8 respectively.
  add_booking('Today Demo Econ', 'today@demo.com', 4, '28B', 'ECONOMY', 320);
  add_booking('Today Demo Biz', 'biz@demo.com', 4, '07A', 'BUSINESS', 980);
  add_booking('Today Demo First', 'first@demo.com', 5, '01A', 'FIRST', 1600);
  add_booking('Tomorrow Demo Econ', 'tomorrow@demo.com', 6, '28C', 'ECONOMY', 320);
  add_booking('Today YUL Econ', 'yul@demo.com', 7, '28A', 'ECONOMY', 180);
  add_booking('Tomorrow YUL Biz', 'yulbiz@demo.com', 8, '07D', 'BUSINESS', 620);
END;
/

COMMIT;

PROMPT Creating helper functions & procedures...

CREATE OR REPLACE FUNCTION fn_available_seats(p_flight_id NUMBER, p_cabin VARCHAR2)
RETURN NUMBER
IS
  v_total NUMBER;
  v_taken NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_total
  FROM seat_layout
  WHERE flight_id = p_flight_id
    AND cabin_class = p_cabin;

  SELECT COUNT(*) INTO v_taken
  FROM ticket
  WHERE flight_id = p_flight_id
    AND cabin_class = p_cabin
    AND status = 'ACTIVE';

  RETURN v_total - v_taken;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RETURN 0;
END;
/

CREATE OR REPLACE FUNCTION fn_booking_total(p_booking_id NUMBER)
RETURN NUMBER
IS
  v_total NUMBER;
BEGIN
  SELECT SUM(fare_amount) INTO v_total
  FROM ticket
  WHERE booking_id = p_booking_id;
  RETURN NVL(v_total, 0);
END;
/

CREATE OR REPLACE PROCEDURE proc_change_seat(
  p_booking_id IN booking.booking_id%TYPE,
  p_seat_no    IN ticket.seat_no%TYPE
) IS
  v_flight_id ticket.flight_id%TYPE;
  v_taken NUMBER;
BEGIN
  SELECT flight_id INTO v_flight_id
  FROM booking
  WHERE booking_id = p_booking_id;

  SELECT COUNT(*) INTO v_taken
  FROM ticket
  WHERE flight_id = v_flight_id
    AND seat_no = p_seat_no
    AND status = 'ACTIVE';

  IF v_taken > 0 THEN
    RAISE_APPLICATION_ERROR(-20010, 'Seat already taken');
  END IF;

  UPDATE ticket
  SET seat_no = p_seat_no
  WHERE booking_id = p_booking_id;
END;
/

CREATE OR REPLACE PROCEDURE proc_cancel_booking(p_pnr VARCHAR2) IS
BEGIN
  UPDATE booking SET status = 'CANCELLED' WHERE pnr_code = p_pnr;
  UPDATE ticket SET status = 'VOID'
  WHERE booking_id = (SELECT booking_id FROM booking WHERE pnr_code = p_pnr);
END;
/

PROMPT Building package with shared procedures/functions...

CREATE OR REPLACE PACKAGE pkg_booking AS
  TYPE t_ticket_summary IS RECORD (
    ticket_number ticket.ticket_number%TYPE,
    seat_no       ticket.seat_no%TYPE,
    cabin         ticket.cabin_class%TYPE
  );

  FUNCTION fx_available_seats(p_flight_id NUMBER, p_cabin VARCHAR2) RETURN NUMBER;
  FUNCTION fx_booking_total(p_booking_id NUMBER) RETURN NUMBER;
  PROCEDURE pr_create_booking(
    p_customer_name   IN customer.full_name%TYPE,
    p_contact         IN customer.contact_info%TYPE,
    p_flight_id       IN flight.flight_id%TYPE,
    p_cabin           IN ticket.cabin_class%TYPE,
    p_seat_no         IN ticket.seat_no%TYPE,
    o_pnr             OUT booking.pnr_code%TYPE,
    o_ticket          OUT t_ticket_summary
  );
  PROCEDURE pr_cancel_booking(p_pnr VARCHAR2);
END pkg_booking;
/

CREATE OR REPLACE PACKAGE BODY pkg_booking AS
  FUNCTION fx_available_seats(p_flight_id NUMBER, p_cabin VARCHAR2) RETURN NUMBER IS
  BEGIN
    RETURN fn_available_seats(p_flight_id, p_cabin);
  END;

  FUNCTION fx_booking_total(p_booking_id NUMBER) RETURN NUMBER IS
  BEGIN
    RETURN fn_booking_total(p_booking_id);
  END;

  PROCEDURE pr_create_booking(
    p_customer_name   IN customer.full_name%TYPE,
    p_contact         IN customer.contact_info%TYPE,
    p_flight_id       IN flight.flight_id%TYPE,
    p_cabin           IN ticket.cabin_class%TYPE,
    p_seat_no         IN ticket.seat_no%TYPE,
    o_pnr             OUT booking.pnr_code%TYPE,
    o_ticket          OUT t_ticket_summary
  ) IS
    v_booking_id booking.booking_id%TYPE;
    v_customer_id customer.customer_id%TYPE;
    v_taken NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_taken
    FROM ticket
    WHERE flight_id = p_flight_id
      AND seat_no = p_seat_no
      AND status = 'ACTIVE';

    IF v_taken > 0 THEN
      RAISE_APPLICATION_ERROR(-20011, 'Seat already sold.');
    END IF;

    INSERT INTO customer(customer_id, full_name, contact_info)
    VALUES (seq_customer.NEXTVAL, p_customer_name, p_contact)
    RETURNING customer_id INTO v_customer_id;

    o_pnr := DBMS_RANDOM.STRING('A', 3) || LPAD(TO_CHAR(DBMS_RANDOM.VALUE(0, 999)), 3, '0');

    INSERT INTO booking(booking_id, customer_id, flight_id, pnr_code, status, paid_flag)
    VALUES (seq_booking.NEXTVAL, v_customer_id, p_flight_id, o_pnr, 'CONFIRMED', 'Y')
    RETURNING booking_id INTO v_booking_id;

    INSERT INTO ticket(ticket_id, booking_id, flight_id, seat_no, cabin_class, fare_amount, status)
    VALUES (seq_ticket.NEXTVAL, v_booking_id, p_flight_id, p_seat_no, p_cabin,
      CASE p_cabin WHEN 'ECONOMY' THEN 320 WHEN 'BUSINESS' THEN 980 ELSE 1600 END,
      'ACTIVE')
    RETURNING ticket_number, seat_no, cabin_class INTO o_ticket;
  END;

  PROCEDURE pr_cancel_booking(p_pnr VARCHAR2) IS
  BEGIN
    proc_cancel_booking(p_pnr);
  END;
END pkg_booking;
/

PROMPT Sample tests (run separately)
-- @sql/tests.sql

SET DEFINE ON;
